export const dishTypes = [
    { value: "", label: 'Any'},
    { value: "Biscuits and cookies", label: 'Biscuits and cookies'},
    { value: "Bread", label: 'Bread'},
    { value: "Cereals", label: 'Cereals'},
    { value: "Condiments and sauces", label: 'Condiments and sauces'},
    { value: "Desserts", label: 'Desserts'},
    { value: "Drinks", label: 'Drinks'},
    { value: "Main course", label: 'Main course'},
    { value: "Pancake", label: 'Pancake'},
    { value: "Preps", label: 'Preps'},
    { value: "Preserve", label: 'Preserve'},
    { value: "Salad", label: 'Salad'},
    { value: "Sandwiches", label: 'Sandwiches'},
    { value: "Side dish", label: 'Side dish'},
    { value: "Soup", label: 'Soup'},
    { value: "Starter", label: 'Starter'},
    { value: "Sweets", label: 'Sweets'},
]

export const cuisines = [
    { value: "", label: 'Any'},
    { value: "American", label: 'American'},
    { value: "Asian", label: 'Asian'},
    { value: "Caribbean", label: 'Caribbean'},
    { value: "Central Europe", label: 'Central Europe'},
    { value: "Chinese", label: 'Chinese'},
    { value: "Eastern Europe", label: 'Eastern Europe'},
    { value: "French", label: 'French'},
    { value: "Indian", label: 'Indian'},
    { value: "Italian", label: 'Italian'},
    { value: "Japanese", label: 'Japanese'},
    { value: "Kosher", label: 'Kosher'},
    { value: "Mediterranean", label: 'Mediterranean'},
    { value: "Mexican", label: 'Mexican'},
    { value: "Middle Eastern", label: 'Middle Eastern'},
    { value: "Nordic", label: 'Nordic'},
    { value: "South American", label: 'South American'},
    { value: "South East Asian", label: 'South East Asian'},
]
